### ISSUE TITLE
Missing autoexec.cfg

### ISSUE THREAD

**Issue by ceno** [LacledesLAN/gamesvr-ioquake3#1]
I think you're missing this file

https://github.com/MarioVilas/ioquake3-server-docker/blob/master/q3a/baseq3/autoexec.cfg

**Comment by ceno** [comment]
I found that having a longer autoexec, with all the common configuration, and then have single cfgs just with game mode configuration was a good way to avoid duplication.

You can see my autoexec.cfg here https://github.com/ceno/Quake3Quest-servers/blob/912cd8442ccdd50038fb631f018961923b54ded6/template.yml#L199

**Comment by JustinBenedick** [comment]
DONE https://github.com/LacledesLAN/gamesvr-ioquake3/commit/18120e2e03016a3075b91f841b2184145a535138
