### ISSUE TITLE
Convert cvars.xlsx to Markdown

### ISSUE THREAD

**Issue by dudleycodes** [LacledesLAN/gamesvr-ioquake3#11]
Try to use markdown table styling. Would be nice to split server and client cvars apart.

Create a separate markdown file (e.g. `cvars.md`) for this documentation \.

**Comment by JustinBenedick** [comment]
How would you feel about writing a document of the most common, useful, and important commands and cvars to administering of a server?  I was looking over the cvars excel file and there was way to much useless info.

**Comment by dudleycodes** [comment]
That's the right way to do it.

Recommend you create sections to distinguish between any server and client cvars.
