### ISSUE TITLE
Fix Instagib Capture The Flag

### ISSUE THREAD

**Issue by dudleycodes** [LacledesLAN/gamesvr-ioquake3#12]

**Comment by JustinBenedick** [comment]
Gonna switch out the instagib plugin, instaulagged was built for 56k modems

**Comment by JustinBenedick** [comment]
just got a big break http://q3files.com/index-7.html

**Comment by JustinBenedick** [comment]
all those were broken,  server version mismatch

**Comment by JustinBenedick** [comment]
OSP already had it. Tested, works and updated documentation.  https://github.com/LacledesLAN/gamesvr-ioquake3/commit/47bcc11eb967bdc98364c1badf493165b20d97cd
