### ISSUE TITLE
Rocket arena fix

### ISSUE THREAD

**Issue by JustinBenedick** [LacledesLAN/gamesvr-ioquake3#13]
Fix for rocket arena . Cant remember why I removed it https://github.com/LacledesLAN/gamesvr-ioquake3/commit/531eea060ead72d649c5610ad510039f8d78e799

**Comment by dudleycodes** [comment]
@JustinBenedick - is this still an issue?

**Comment by JustinBenedick** [comment]
It still won't work going to leave it out for now

**Comment by dudleycodes** [comment]
Then we should remove all references in `readme.md` - and any straggling files related to it, right?
